model:
  base_learning_rate: 1.0e-6
  target: imaginairy.modules.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False # we set this to false because this is an inference only config

    scheduler_config: # 10000 warm-up steps
      target: imaginairy.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1 ] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: imaginairy.modules.diffusion.openaimodel.UNetModel
      params:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        legacy: False

    first_stage_config:
      target: imaginairy.modules.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: imaginairy.modules.clip_embedders.FrozenCLIPEmbedder


data:
  target: imaginairy.train.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    num_val_workers: 0 # Avoid a weird val dataloader issue
    train:
      target: imaginairy.datasources.single_concept.SingleConceptDataset
      params:
        concept_label: "photo of Bryce"
        concept_images_dir: "./other/images/bryce/cropped"
        class_label: "photo of a man"
        image_transforms:
        - target: torchvision.transforms.Resize
          params:
            size: 512
            interpolation: 3
        - target: torchvision.transforms.RandomCrop
          params:
            size: 512
#        - target: torchvision.transforms.RandomHorizontalFlip
#    validation:
#      target: ldm.data.simple.TextOnly
#      params:
#        captions:
#        - "A pokemon with green eyes, large wings, and a hat"
#        - "A cute bunny rabbit"
#        - "Yoda"
#        - "An epic landscape photo of a mountain"
#        output_size: 512
#        n_gpus: 2 # small hack to sure we see all our samples


lightning:
  find_unused_parameters: False

  modelcheckpoint:
    params:
      every_n_train_steps: 500
      save_top_k: -1
      monitor: null

  callbacks:
    image_logger:
      target: imaginairy.train.ImageLogger
      params:
        batch_frequency: 100
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_all_val: True
        log_images_kwargs:
          use_ema_scope: True
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 1
          unconditional_guidance_scale: 7.5
          unconditional_guidance_label: [""]

  trainer:
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1

